### PR TITLE
Update es6.xml

### PR DESCRIPTION
**Pull request by inoperable**
few changes, some additions

### CODE REVIEW

**Comment by blakedietz** [comment]
Hey just saw this, I'll review it in a bit.

**Review by blakedietz — COMMENTED** [review]
Unfortunately these changes don't align with the initial project that was being used for reference. This project is based on https://atom.io/packages/es6-javascript. The shorthands that you used in the pr are not in that reference. A goal of this project is to have a set of macros that are shared across editors. With that in mind these changes do not align with the intended purpose of the project.

Thank you for submitting a pr though! I really appreciate it. If you have any other changes or feedback, please feel free to comment or let me know!

**Comment by inoperable** [comment]
The shorthands I used are more of personal preference and my trying to feel more like vim with snippets with ideavim. I'll take a look at the reference and tune it to that style, would be good if you could point out the obvious things I should take into account- no need to reinvent the wheel, what I'd like to see is that more ppl will contribute, just set the rules and others will follow.

We could build all es6+ frequent/commonly used shorthands and expand those to patterns or whatever. This could grow really quick - I frankly don't understand why there isn't already a live template collection somewhere. I bet if this grows jetbrains would spread the message. 

I'd love to have one repo with snippets for all jetbrains ide's- too often I had my 5 min of profanity filled realising that I just (again) deleted my preferences including all of the live templates and key mappings too- since they reside somewhere I always forget to cd into.

**Comment by blakedietz** [comment]
@jankun I'm glad to see you're interested. I agree that it's weird that there aren't any other live template repos. My eventual goal with this would be to support es6+ features and maybe some common application patterns.

I already started toying with the idea of a set of [ducks](https://github.com/erikras/ducks-modular-redux) live templates. We could just make each of those a different group of live templates housed under this which allows for people to just pick and choose the groups they want to enable.

Perhaps we could start working on a `CONTRIBUTING.md`. I'd love your help in making this repo even more awesome. I'll address the rest of your feedback in a comment later if that's alright.

**Comment by inoperable** [comment]
Agreed then- drop me a line either here or directly p[at]jankun.org

**Pull request closed without merging**
